name: biketouren
markdown: redcarpet
pygments: false
exclude: 
- run.sh
- .gitignore

prose:
  rooturl: '_posts'
  siteurl: 'http://chbiker.github.io'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
          help: "Post date as YYYY-MM-DD HH:MM:SS"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Touren"
              value: "tour"
            - name: "Tips"
              value: "tips"
      - name: "tour"
        field:
          label: "Tour"
          element: "number"
      - name: "length"
        field:
          label: "LÃ¤nge"
          element: "number"
      - name: "up"
        field:
          label: "Up"
          element: "number"
      - name: "down"
        field:
          label: "Down"
          element: "number"

